### ISSUE TITLE
Initial state based on object attribute

### ISSUE THREAD

**Issue by wafcio** [gocardless/statesman#110]
Is it possible to set initial state based on attribute? In README I see example with static initial state, in closed issues I see examples with static initial state and "initial transaction" which give possible to change initial state, but this solution is little weird, because initial state should be connected with all states (in this case).

Because statesman have StateMachine objects as external classes I think it is good to add possible to set initial_state (for example in constructor)

**Comment by chrise86** [comment]
Sorry to drag up an old thread, but having multiple `initial_states` would be useful to me too. I have a situation where an object may be created by 2 different entities with differing authorization levels. When the one entity creates an object, it needs to be in one state as the entity with more power needs to review/triage it. When the higher up entity creates an object, that step is not needed, therefore requiring a different initial state. There is an attribute that gets set on the object to determine this.
