### ISSUE TITLE
Check ruby toolbox changes (most importantly category: State Machines)

### ISSUE THREAD

**Issue by PragTob** [gocardless/statesman#113]
Hi there,

just found your gem by accident :) Looks really nice.

Lots of people use https://www.ruby-toolbox.com to look for gems and there your gem isn't yet listed under state machines: https://www.ruby-toolbox.com/categories/state_machines

There are a bunch of modification requests to add that category to the gem, you can review them here (after you probably "own" the project or something): https://www.ruby-toolbox.com/projects/statesman/modifications

Would be nice to have such a cool and active project there.

Thanks and cheers!
Tobi

**Comment by appleton** [comment]
+1 from me. I don't seem to be able to accept the modifications though, maybe someone still in the @GoCardless org can do it?

**Comment by isaacseymour** [comment]
I've just signed in to Ruby Toolbox and can't find any way of accepting the changes. I'll email the guy who made it.

**Comment by greysteil** [comment]
@colszowka - none of us can figure out how to accept the suggested changes, but we'd love to. Can you help?

**Comment by greysteil** [comment]
Closing as stale :(

**Comment by colszowka** [comment]
Finally fixed it - sorry everyone, I'm having trouble finding the time to keep up with toolbox things at the moment, but I'm working on opening things up soon-ish so I can get my bottlenecky self out of the way!

https://www.ruby-toolbox.com/projects/statesman

**Comment by greysteil** [comment]
Nice, thanks @colszowka !
