### ISSUE TITLE
Documentation for after_commit type callbacks

### ISSUE THREAD

**Issue by PragTob** [gocardless/statesman#116]
Hi there!

First thanks a lot for being so active on my other issues/PR :) I :heart: that!

Browsing the source code I found there is an `after_commit` argument to `after_transition` which creates an `after_commit` type callback instead of the `after` type. The README does not mention this, would be nice to add some docs about this.

Might be important for people, for whom his kind of callback is important.

For reference I'm talking about [this](https://github.com/gocardless/statesman/blob/master/lib/statesman/machine.rb#L98) or pasted in here:

```ruby
     def after_transition(options = { from: nil, to: nil,
                                       after_commit: false }, &block)
        callback_type = options[:after_commit] ? :after_commit : :after

        add_callback(
          options.merge(callback_class: Callback, callback_type: callback_type),
          &block)
      end
```

Cheers,
Tobi

edit: of course it does what I think it does, very nice code, thanks!

**Comment by isaacseymour** [comment]
Hah, maybe set expectations too high ;) I'll do my best to get a PR documenting this in this evening but can't make any promises. PR from you would be very welcome!

**Comment by isaacseymour** [comment]
Also, now you've mentioned it, the API of that is a bit skank. I'd expect:
```ruby
after_transition_committed do |model, transition|
  # things
end
```
rather than 
```ruby
after_transition after_commit: true do |model, transition|
  # things
end
```
but we can't change that without bumping to v2 which doesn't seem worth it.

**Comment by isaacseymour** [comment]
Actually, see #117

**Comment by PragTob** [comment]
@isaacseymour you could add the method in a minor release while keeping the old hash version around and maybe printing a deprecation warning for the old hash style syntax (or just keep it around) :) Should be rather easy!

Thanks for the documentation!
