### ISSUE TITLE
State-driven instance behavior

### ISSUE THREAD

**Issue by mtarnovan** [gocardless/statesman#118]
https://github.com/pluginaweek/state_machine has this and I find it very useful: the ability to define instance methods based on state.

Any plans for such a feature in statesman?

**Comment by isaacseymour** [comment]
Hi Mihai, I don't really see how that adds much value. In fact, I find:
```ruby
def speed
  case current_state
  when 'parked' then 0
  when 'idling', 'first_gear' then 10
  ...
end
```
to be much clearer than redefining the whole method based on state, although I may have misunderstood what you mean by state-driven instance behaviour.

**Comment by mtarnovan** [comment]
Thanks for the reply Isaac. Yes, that's what I mean. Here's an example from state_machine's documentation:

```ruby
...
    state all - [:parked, :stalled, :idling] do
      def moving?
        true
      end
    end

    state :parked, :stalled, :idling do
      def moving?
        false
      end
    end
...
```

In practice, I find this useful for implementing different validations based on state, e.g.

```ruby
class User
...
  state :new do
    validates :email, presence: true
  end

  state :signed_up do
    validates :email, :name, presence: true
  end
```

Hope this makes sense.

**Comment by isaacseymour** [comment]
You example makes more sense that the one in the docs for that gem, but I still think the alternative is still cleaner:
```ruby
class User
  validates :email, presence: true
  validates :name, presence: true, if: :signed_up?

  def signed_up?
    state_machine.current_state == 'signed_up'
  end
  
  ...
end
```

**Comment by mtarnovan** [comment]
Of course you can implement it your way too, but I found that grouping state related behaviour in the state block leads to very readable code on a project I used that gem for. In the end this is more or less just syntax sugaring and not a must-have. I'll close the issue, thanks!
