### ISSUE TITLE
"in_state" scope takes long time to run

### ISSUE THREAD

**Issue by bfaguy** [gocardless/statesman#121]
we have a model called orderproduct that uses statesman.
whenever we perform a `Orderproduct.in_state()`, it is taking longer than expected to run. 
We have upwards of 700,000 to 800,000 records for this model. 
Is there anyway to speed up this scope?

thanks

versions
ruby '2.1.2'
gem 'rails', '4.1.2'
statesman (0.8.3)

**Comment by isaacseymour** [comment]
Hi @bfaguy, this is an issue we ran into recently. We've internally implemented a solution which uses database triggers to maintain a `most_recent` flag on the most recent transition for each model. This means the query looks something like:
```sql
SELECT p.* 
FROM order_products p 
JOIN order_product_transitions t 
  ON t.order_product_id = p.id AND t.most_recent = 't' 
WHERE t.to_state = 'sent';
```
which is crazy fast when compared to the double-`LEFT OUTER JOIN` used by the current `in_state` implementation.

I'm working on a way of doing this within Statesman which is database-agnostic.

**Comment by bfaguy** [comment]
Hi @isaacseymour Thank you for your quick response. 
Hope you can find a work around soon.

**Comment by greysteil** [comment]
@bfaguy - https://github.com/gocardless/statesman/pull/132 is designed to address this (and is similar to the solution we're using internally).

**Comment by bfaguy** [comment]
thank you @greysteil. We did find a workaround via our own code but your solution is greatly appreciated. @pdbradley

**Comment by greysteil** [comment]
Closing now that #132 and #137 are included in a release.
