### ISSUE TITLE
Speeding up Model.in_state() by not persisting transition history

### ISSUE THREAD

**Issue by pdbradley** [gocardless/statesman#122]
Hi @isaacseymour and anyone else;

We are having trouble with the long executing in_state method and I realized this morning that we do not even really need the transition *history* logged, necessarily.  Just the state.

If you only cared about guarding the transitions and not persisting the history, what is the best way to simply store the final state of the object?  Is it best to just store that in a column on the model and then your in_state query just becomes a query on that column?

**Comment by isaacseymour** [comment]
You could just use:
```ruby
before_transition do |model, transition|
  model.current_state = transition.to_state
end
```
in your state machine to denormalise the current state onto the model, and then filter on this column super-speedily.

**Comment by pdbradley** [comment]
this seems a great solution.  thanks!

**Comment by barisbalic** [comment]
Closing because everyone seems to be happy.
