### ISSUE TITLE
Explanation purpose of the sort_key

### ISSUE THREAD

**Issue by dmitry** [gocardless/statesman#128]
Can anyone give an explanation why do we need to add `10` to `sort_key` for every state transition, instead of increment it by 1? For example: https://github.com/gocardless/statesman/blob/18854e3064794f049d02ea92d38ea2af3cb7ed83/lib/statesman/adapters/active_record.rb#L76

As I understand `sort_key` have only two purposes:

- prevent from race conditions;
- sort states (find last one, have a history of states in a proper order).

Is there are other hidden reasons for `sort_key`?
In other case, I don't understand why there are `sort_key + 10` in implementation.

**Comment by isaacseymour** [comment]
Hi @dmitry, I think the main reason for there being spacing in the sequence of sort keys is to help with backfilling data when adding a new state between two existing ones. There are probably some other reasons I haven't thought of but I don't think there are any reasons not to have the extra spacing. Is it causing an issue for you?

**Comment by barisbalic** [comment]
Although this decision was made before I joined, I believe it just provides a kind of safety net.  If you have a transition with a `sort_key` value of 10, and another of 20, it is possible to insert a transition, and thus a state, between them by giving it the `sort_key` of 15.

I don't think this is something that should be factored into daily usage.  It was a good spot and a good question, thanks @dmitry

**Comment by isaacseymour** [comment]
Hah, looks like @barisbalic agrees :P

**Comment by dmitry** [comment]
@isaacseymour and @barisbalic thank you for the very quick answers! :+1: 
It also what I have thought, but haven't found direct functionality inside the library, that gives ability to insert state in the middle of states.
No issues at all, just want to understand library from all the sides before I will use it :)
