### ISSUE TITLE
can i get all defined states and transitions in state machine?

### ISSUE THREAD

**Issue by feitian124** [gocardless/statesman#146]
if i have below classes:
```
class OrderStateMachine
  include Statesman::Machine
  state :created, initial: true # 拍下商品
  state :payed                  # 付款到万流
  state :shipped                # 卖家发货
  state :received               # 确认收货
  state :finished               # 完成
  state :cancelled              # 取消
end

class Order < ActiveRecord::Base
  include Statesman::Adapters::ActiveRecordQueries
end
```

can i get all defined states in Order?

**Comment by barisbalic** [comment]
Hi @feitian124, any State Machine you create should have a `.states` class method that returns it's states.

For example, `OrderStateMachine.states` should give you back the states you have defined.  Is that what you were looking for?

**Comment by feitian124** [comment]
yes, that's what i need, thank you.
i only tried invoke .states by an instance then find it is undefined..

**Comment by barisbalic** [comment]
No problem, happy hacking!
