### ISSUE TITLE
Could not find generator 'statesman:add_most_recent'

### ISSUE THREAD

**Issue by dougfarre** [gocardless/statesman#151]
Hi, Just updated to latest version  statesman-1.2.2.gem (100%) and tried to add most recent column.  getting error about that generator not existing.  thanks.

**Comment by isaacseymour** [comment]
Did you manage to fix this @dougfarre ?

**Comment by aliibrahim** [comment]
This is still an open issue btw! The generator is not found when the command is run. So essentially this [guide](https://github.com/gocardless/statesman/wiki/Adding-a-%60most_recent%60-column-to-an-existing-model) is causing issues
