### ISSUE TITLE
Reading current_state from the parent model

### ISSUE THREAD

**Issue by jorge-marques** [gocardless/statesman#154]
Hi, I have a use case where I don't really need to keep track of transition history. I'd like to simply store the current_state on the parent model. Is this possible? I know I can store the current state using a callback, but can I have statesman read the current state from the parent model, in case the application goes down?

**Comment by isaacseymour** [comment]
Hi @jorge-marques, one of the core features of Statesman is that it records history, so it's not possible to use it without doing so, and I don't think this is ever something we'd look to change.

**Comment by jorge-marques** [comment]
Well, I asked mostly because I am already using statesman in this project, and would prefer not to bring in another dependency by using another state machine gem. I suppose I'll just record the history anyway.
Thank you.
