### ISSUE TITLE
Skipping callbacks

### ISSUE THREAD

**Issue by jorge-marques** [gocardless/statesman#155]
Is there way to skip before/after transition callbacks?

**Comment by isaacseymour** [comment]
You could use a `next if some_condition` in your callback. What's the scenario you're trying to skip them in?

**Comment by jorge-marques** [comment]
My callbacks just send some emails.
I'm migrating what was previously handled by a boolean field to a state machine. When running the task that migrates the data, it would be useful to have a `skip_callbacks` option in the `transition_to` method, so that the emails don't get sent. I realize it's a very narrow use case, and that there are ways around it, but it might be useful in some cases.

**Comment by isaacseymour** [comment]
You could achieve this with something like:
```ruby
after_transition to: :state do |thing, transition|
  next if transition.metadata[:skip_callbacks]
  send_email
end

state_machine.transition_to!(:state, skip_callbacks: true)
```

**Comment by jorge-marques** [comment]
Totally forgot about the metadata. Thanks a lot!
