### ISSUE TITLE
[MySQL] Uniqueness constraint on most recent index

### ISSUE THREAD

**Issue by robinjfisher** [gocardless/statesman#157]
Hi,

Perhaps I'm missing something but I'm struggling to use more than 3 states in light of the uniqueness constraint on the most recent index.  As I understand it, the index key is constructed from the id of the model and the boolean flag from the most_recent column.  My model relates to an absence, and I have the following states:

Unapproved (default state)
Provisionally Approved (sets most_recent to 1 giving key id-1)
Approved (sets most_recent to 1 giving 2 keys: id-0 for the original transition and id-1 for the transition to approved)
Cancelled - fails on transition here because a duplicate index key is created.

Is this the intended behaviour?  For the time being I've dropped the uniqueness constraint on the index but I understand this will then stop the most_recent column being used for queries.

Thanks

Robin

**Comment by isaacseymour** [comment]
Statesman automatically sets all existing transitions for the model to have `most_recent = false` before running the transition ([see here](https://github.com/gocardless/statesman/blob/master/lib/statesman/adapters/active_record.rb#L64)), so this should only be a problem if you're manually inserting transitions. @greysteil and @petehamilton know much more about the `most_recent` stuff than I do though!

**Comment by robinjfisher** [comment]
Thanks @isaacseymour. I'm not inserting manual transitions - just a call to `@absence.transition_to!(:cancelled).  Not urgent as I can always reinsert the constraint on the index.  Happy to share additional code if it might be useful.

**Comment by jackfranklin** [comment]
@robinjfisher sounds very odd - definitely not something that should be happening. If you could share some code that should help us debug :+1:

**Comment by robinjfisher** [comment]
Thanks @jackfranklin. [Here's a gist](https://gist.github.com/robinjfisher/97e48f126b940d9db767) of the console backtrace; state machine class and absence transition class.

Any help appreciated.

Robin

**Comment by isaacseymour** [comment]
Ok, looks like the index that was created is a full one, rather than just partial where `most_recent` is true. Could you add the code used to create the index on `parent_id` and `most_recent`?

**Comment by isaacseymour** [comment]
Aha, I think this is an issue with MySQL's storage of booleans (which doesn't really exist properly). [This line](https://github.com/gocardless/statesman/blob/master/lib/generators/statesman/templates/add_constraints_to_most_recent_migration.rb.erb#L5) creates a partial index where `most_recent` is truthy. In Postgres, this is fine because `most_recent` is a boolean column, but in MySQL it's stored as a 1-bit integer, and I suspect that 0 is truthy, which is a bit annoying. If you alter your migration to have `where: "most_recent = 1"` then I think it'll work.

We should definitely fix that migration to work with MySQL too, but that's actually kinda hard (`where: "most_recent = 1"` would not work in Postgres because 1 is not a boolean). Maybe we'll just have to have separate MySQL and Postgres migration generators.

**Comment by robinjfisher** [comment]
Thanks @isaacseymour. Will re-run the migration as you indicate and report back.

**Comment by robinjfisher** [comment]
It would appear that `where: 'most_recent = 1'` doesn't work in MySQL.  Running the migration with that amend produces the same duplicate key error when it tries to generate the index. I've had a dig in the MySQL docs to see if I can create the index manually but no luck yet.

**Comment by isaacseymour** [comment]
https://github.com/rails/rails/issues/18106

Looks a lot like MySQL doesn't support partial indexes :(

**Comment by robinjfisher** [comment]
Yes, I've just reached that conclusion myself. :( Thanks for your help though! :+1:

**Comment by greysteil** [comment]
Ah man, this is really annoying.

Can probably get around it using null values. http://stackoverflow.com/questions/3712222/does-mysql-ignore-null-values-on-unique-constraints

**Comment by greysteil** [comment]
@robinjfisher - I've put together a fix at https://github.com/gocardless/statesman/pull/158, and we'll release it as a new version tomorrow.

**Comment by petehamilton** [comment]
What a pain. Kudos to @greysteil for putting in a fix for this one.

**Comment by robinjfisher** [comment]
@greysteil @isaacseymour @petehamilton Wow. Thanks guys. Really appreciate it.

**Comment by greysteil** [comment]
@robinjfisher - all released in v1.2.3. Let us now if you have any more issues, and thanks for the bug report.
