### ISSUE TITLE
Can't setup model as part of initial state

### ISSUE THREAD

**Issue by DCameronMauch** [gocardless/statesman#159]
I want to do something like this:

```ruby
foo_sm = FooStateMachine.new(Foo.new)
```

I would expect the state machine to be in the initial state, which it is.  But I would also expect the model to have it's attributes reflect that initial state.  I totally see how I can use after_transition blocks to update the model attributes, but the initial state is apparently not considered a transition.  So how do we setup the model attributes on the initial state?

I could do this with default attribute values in the model, but then some of my state logic is in the model.  Or I could setup the model before I pass it to the state machine, but then I have some state logic in a controller or something, which is even worse.

**Comment by rgerard** [comment]
@DCameronMauch it's too bad you closed this, as I'm having the same issue. The FAQ addresses "Storing the state on the model object", but their logic only works for transitions, not initial state. Did you find a workaround? I am just manually setting the initial state using a `before_create` in my model, but that's not optimal.
