### ISSUE TITLE
What's the best way to retrieve records belonging to a statesman model in a certain state?

### ISSUE THREAD

**Issue by KBalderson** [gocardless/statesman#160]
I want to retrieve all events belonging to completed orders for a given customer.

My Customer model has many Orders (for which states are controlled by statesman), and each order has_many Events.

Using has_many :through, I want to retrieve events for only orders which have been "shipped."

This is as far as I've gotten

```ruby
  class Customer < ActiveRecord::Base
    has_many :shipped_orders, -> { in_state(:shipped) }, class_name: "Order"
    has_many :shipped_events, through: :shipped_orders, source: :events
  end
```

I get the following error with this:

    PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "last_transition"

**Comment by isaacseymour** [comment]
I think you should just be able to do:
```ruby
class Order < ActiveRecord::Base
  has_many :events

  scope :shipped, -> { in_state(:shipped) }
end

class Event < ActiveRecord::Base
  belongs_to :order
end

class Customer < ActiveRecord::Base
  has_many :orders
  has_many :events, through: :orders
  
  def self.shipped_orders
    orders.in_state(:shipped)
  end

  def self.shipped_events
    events.joins(:order).merge(Order.shipped)
  end
end
```

**Comment by KBalderson** [comment]
Worked perfectly. Thanks!
