### ISSUE TITLE
add i18n support

### ISSUE THREAD

**Issue by feitian124** [gocardless/statesman#163]
hi, how about add i18n support?

**Comment by isaacseymour** [comment]
Hi @feitian124 - what would you it internationalise? I can't think of any user -facing messaging in the gem (although probably just me being slow!)

**Comment by feitian124** [comment]
currently what i met are the error messages, they are hard coded..

**Comment by isaacseymour** [comment]
Error messages in the exceptions? I think that's fine - those should not be exposed to end-users, so don't need to be internationalised.
