### ISSUE TITLE
Should you write shortcut methods in your models?

### ISSUE THREAD

**Issue by LimeBlast** [gocardless/statesman#167]
I don't think this is a statesman specific question, but it does relate to my usage of the statesman gem, so I apologise if this is out of scope.

If we're following the example set-up stated in the readme file, I'm wondering what people's opinion on adding some shortcut methods to the `Order` model are? Specifically I'm thinking something along the lines of
```ruby
class Order < ActiveRecord::Base
    --- snipped from readme ---

   def cs
       state_machine.current_state
   end
end
```

Allowing for `Order.first.cs` over `Order.first.state_machine.current_state`

I'm not sure what the convention for this sort of thing is, but I was under the impression that the Law of Demeter suggests the latter is bad, and the former is better, but I really don't know - so I'm keen on hearing how people actually use this in the wild.

Thanks.

**Comment by isaacseymour** [comment]
We tend to either define methods like that explicitly on models, or use `delegate :current_state, to: :state_machine`. It can also be good practice to define methods for common transitions, if they're non-trivial calls (say, involve some metadata). This is of course personal preference, but I tend to find it makes for cleaner code.

**Comment by LimeBlast** [comment]
Thank you for your answer, that sounds like a good approach to me. Cheers.
