### ISSUE TITLE
Migration generated by add_constraints_to_most_recent doesn't work in MySQL

### ISSUE THREAD

**Issue by timothyp** [gocardless/statesman#170]
There are two reasons for this:
* disable_ddl_transaction! is not supported by MySQL.
* "algorithm: :concurrently" for index creation is PostgreSQL-only.

The easy workaround (which I initially used) is of course just to remove these from the generated migration.

Making generation of these elements conditional is pretty simple.  What is more interesting is testing.  The straightforward approach will lead to some new fixture files.  Currently there is one pair for with-and-without partial indexes.  One approach would be to add 2 more pairs: with-and-without ddl transaction support and with-and-without algorithm:concurrently support.  It could be argued that to be thorough, combinations should be tested too, but that leads to an explosion of fixtures!  Any thoughts?

**Comment by isaacseymour** [comment]
Hmm, I think it's probably reasonable to have one per actual feature-set, i.e. one for MySQL and one for Postgres. Possibly also ones for SQLite, Oracle, SQL server, etc., although I have no idea how this works.

This raises an interesting point about these migrations though - we can't really comment on how they will perform on systems other than Postgres. From some brief googling, it looks like this migration cannot be performed without downtime on most MySQL setups. I think I'm :-1: on generating migrations which could cause people downtime if they're blindly deployed. Maybe we should just add a note saying "if you're not using Postgres, you will have to adapt these, and be careful about causing downtime".
