### ISSUE TITLE
Mysql2::Error: Duplicate entry

### ISSUE THREAD

**Issue by breiko83** [gocardless/statesman#174]
Switching my project from development (sqlite) to production (mysql) I get this error in a state transition.

    Mysql2::Error: Duplicate entry '7-0' for key 'index_deal_transitions_parent_most_recent'

This seems to be caused by the index 'most_recent'. Removing the index from the table fix the problem.

**Comment by isaacseymour** [comment]
I think this is probably the same issue as #157. If that's the case, you'll need to change your schema so that the `most_recent` column allows `NULL`, and uses that instead of false. Please reopen if I'm wrong though (which is quite likely as I know very little about MySQL!)
