### ISSUE TITLE
A machine's `available_events` are not filtered by guards

### ISSUE THREAD

**Issue by joeroot** [gocardless/statesman#181]
I think this is an issue, at least based upon my interpretation of `available_events`. 

The list of events returned by `available_events` is not filtered based upon a machine's guards, which means the event's returned may not necessarily be valid.

**Comment by joeroot** [comment]
This is the super-hacky patch I've been using, however it's almost certainly sub-optimal DB query wise.

    module Statesman
      module Machine
        def available_events
          state = current_state
          self.class.events.select do |_, transitions|
            transitions.key?(state) and
              transitions[state].map{|new_state| self.can_transition_to?(new_state)}.all?
          end.map(&:first)
        end
      end
    end

**Comment by isaacseymour** [comment]
That looks like a legit patch to me. If you have time to put together a spec & submit a PR I'd be :+1:

**Comment by greysteil** [comment]
Closing - events are planned to be split out into a separate companion gem.

**Comment by greysteil** [comment]
Quick update - split out is [here](https://github.com/gocardless/statesman-events)

@joeroot - hope all's well with you! Pull requests very welcome.
