### ISSUE TITLE
ActiveRecord#reload interactions with memoization example

### ISSUE THREAD

**Issue by hderms** [gocardless/statesman#186]
In the following example you show a memoized state machine instance variable being used (with good reason):

```
class Order < ActiveRecord::Base
 #...
  def state_machine
    @state_machine ||= OrderStateMachine.new(self, transition_class: OrderTransition)
  end
 #...
end
```

In general this behavior is welcome for efficiency reasons, but in specific cases it leads to possible bugs unless the user is familiar with Statesman. In particular, reloading a model that has a memoized instance variable can lead to strange behavior. Additionally, the fact that the Sql storage adapter memoizes the `#last` transition accessor makes it easy to introduce race conditions if events are triggered through a child relationship as well as through the model that corresponds to a state machine like so:

```
foo.bar.trigger!(:some_event)
foo.reload
foo.trigger!(:some_other_event)
```

has behavior that some users might find surprising. I don't have any concrete solutions because there's  no guarantee hooking into `#reload` makes sense in all contexts (though it might make sense to have a n includable module that would do so). In addition, the memoization of `#last` on the adapter is probably a practical requirement based on how often that attribute may be accessed throughout the lifecycle of a transition being created. Any insight into ways that the API could be made to be more intuitive in some of these edge cases?

**Comment by isaacseymour** [comment]
This is one of the most annoying things in Statesman imo, but I think it's pretty hard to work around (we need to cache the transitions inside Statesman to avoid races if I remember correctly). I'll take a look into making the state machine just rely on the Rails cache of the transition association, but I don't really understand Rails internals enough to do that with confidence :/

**Comment by hderms** [comment]
@isaacseymour yeah I know I couldn't think of any clean solution that worked for all of the requirements without being messy. I think you guys are currently handling it in a good way so I'm wondering if just adding a note to the documentation would be acceptable to at least give people a warning.

**Comment by isaacseymour** [comment]
I can't think of a reason why we'd need to use `.reload` outside of tests, so we tend not to run into this issue in app code. Tend to get around it in test by doing a hard reload (`instance = Model.find(instance.id)`) instead of just `instance.reload`. Not the best though.

**Comment by hmac** [comment]
Statesman 2.0 allows you to pass `force_reload: true` to `Machine#current_state` and `Machine#last_transition`. This will bust the cache of the last transition and should fix this issue.
