### ISSUE TITLE
Model scopes with several state machines

### ISSUE THREAD

**Issue by vmotsak** [gocardless/statesman#187]
Lets say I have two state machines on my model

```
class User < ActiveRecord::Base

   def state_machine_x ..
   def state_machine_y ..
end
```

what is best way to have `Statesman::Adapters::ActiveRecordQueries` add scopes for both of them
to have something like `User.in_x_state`, `User.in_y_state`?

**Comment by isaacseymour** [comment]
Hmm, I don't think that's possible with the current implementation of `ActiveRecordQueries`. There would be quite a nice refactor to convert it from a module which gets included into a class which takes a model class, the transition relation name (and maybe some other parameters), and had `in_state` methods on it, but I'm not going to have time to do that right now.

Assuming you've got the `most_recent` stuff set up, the queries are actually pretty simple, e.g.:
```
scope :in_x_state, ->(state) { joins(:transition_relation).where(transition_relation: { most_recent: true, to_state: state}) }
```
(assuming `state` is _not_ the initial state - if it is you have to make the join a `LEFT OUTER JOIN` also allow `transition_relation.id` to be `NULL`)

**Comment by vmotsak** [comment]
Something like this?
``` 
  scope :in_x_state, ->(states) { StatesmanQueries.new(self, XTransition,:new).in_state(*states) }
```

```
class StatesmanQueries 
  def initialize(model_class, transition_class, initial_state)
    @model_class = model_class
    @transition_class = transition_class
    @initial_state = initial_state
  end

 # retain  code of current  ActiveRecordQueries module just applied to instance vars 
  private

  def in_state_with_most_recent(states)
    @model_class.joins(most_recent_transition_join).
....
```

**Comment by isaacseymour** [comment]
Yeah I think that would most likely work, although there's some crazy reflection stuff in there to work out how to join the right association if you've used non-default association names, so it might be harder than it looks at first...

**Comment by hmac** [comment]
Closing this since it's quite old. Feel free to reopen if you're still hitting this issue!
