### ISSUE TITLE
Simple state persistence in model

### ISSUE THREAD

**Issue by andyw8** [gocardless/statesman#199]
I'm trying out Statesman with the ActiveRecord adaptor. I don't need to keep a record of past transitions, so I've initialized my state class using simply `OrderStateMachine.new(self).`

I've added an `after_transition` callback so that changes are persisted to DB, and that appears to work correctly.

However, when initializing `OrderStateMachine` from an existing, persisted `Order` instance, `order_state_machine#current_state` returns nil. How should I tell the state machine to read the `state` column in my orders table and use as the current state?

**Comment by andyw8** [comment]
I see a similar question was asked in #154.

**Comment by greysteil** [comment]
Hi Andy,

A key feature of Statesman is that it stores state transitions in a separate table, allowing it to offer database-level duplication protection. If you don't want to store transitions in that way, and instead want to store state on your model directly, then this probably isn't the right library for you. It would be a big change to the core of statesman to support that functionality.
