### ISSUE TITLE
Rails 5 Support

### ISSUE THREAD

**Issue by brunoalano** [gocardless/statesman#202]
I've checked that Rails 5 doesn't support more `cast_type` in AbstractMysqlAdapter::Column, and statesman uses it on:
https://github.com/gocardless/statesman/blob/master/lib/statesman/adapters/active_record.rb#L112

How can I replace it?

**Comment by kenchan0130** [comment]
I have not neatly checked yet, I see a commit in the Rails 5 with this:
https://github.com/rails/rails/commit/158c7eb1d61a28452e0aafd1e05314352eea2749#diff-c226a4680f86689c3c170d4bc5911e96R10

We might be able to use the `fetch_type_metadata` method. 

How about this?

**Comment by greysteil** [comment]
Good catch guys. Should be fixed by https://github.com/gocardless/statesman/pull/208.
