### ISSUE TITLE
Fail silently on "final" state.

### ISSUE THREAD

**Issue by michaelminter** [gocardless/statesman#203]
If I have 3 states that look like: `[:init, :working, :complete]` I want `:complete` to not be able to go backwards. But I don't want warning to get fired off on this transition either.

So far I've got:

```
state :init, initial: true
state :working
state :complete

transition from: :init, to: :working
transition from: :working, to: :complete
transition from: :complete, to: states.map(&:to_sym)

guard_transition(from: :complete) do |object|
  false
end
```

`object.transition!(:working)` throws a `Statesman::GuardFailedError` when called.

How can I write this, in a way that `transition!(:down)` will fail quietly (*true*), and without changing state?

Would it be worth it to add an attribute to `state` like: `state :complete, locked: true` that returns true for any transitions that match that state?

Thanks!

**Comment by greysteil** [comment]
Hi @michaelminter,

Thanks for the question. I think you want to handle this kind of logic outside of the state machine. Perhaps the simplest way would be to use `object.transition_to(:down) unless object.in_state?(:complete)`?

I'd also lose the allowed transitions from `complete`, so your state machine would look like:

```
state :init, initial: true
state :working
state :complete

transition from: :init, to: :working
transition from: :working, to: :complete
```

If you're worried about races with the above approach, you could wrap calls in `Statesman::Machine.retry_conflicts`.
