### ISSUE TITLE
Transitions don't require a new transaction

### ISSUE THREAD

**Issue by MSch** [gocardless/statesman#205]
https://github.com/gocardless/statesman/blob/master/lib/statesman/adapters/active_record.rb#L73

If `ActiveRecord::Base.transaction` is called while already inside a transaction it does not create a "nested" transaction (actually a savepoint) c.f. [Nested Transactions](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html) in the Rails documentation

This means the following code will lead to an incorrect state in the DB:

``` ruby
MyModel.transaction do
  begin do
    my_model.transition_to(:something_that_fails)
  rescue Error
    # handle it somehow, expecting the transition to have been rolled back
    # but because we were already in a tx nothing happened, the db has been modified
    # and all guarantees are now void
  end
end
```

I actually ran into the opposite issue with aasm a while back, so the ideal solution would be to make the `requires_new` setting on the AR transaction configurable, c.f. https://github.com/aasm/aasm/issues/107

**Comment by hmac** [comment]
@MSch are you able to provide steps to reproduce or (even better) a failing test case for this? What you've described makes sense in the abstract (you could get into a state where you think a transition has rolled back but it hasn't) but I'm struggling to make that happen in reality.

**Comment by hmac** [comment]
I think it makes sense to have `requires_new: true` on all transactions - Rails' fake nested transactions are pretty much never what you actually want.
