### ISSUE TITLE
Capturing the actor for a transition

### ISSUE THREAD

**Issue by lukeredpath** [gocardless/statesman#213]
As part of my business logic its important for me to capture the actor in a transition, i.e. the user who performed the action that resulted in a transition.

It seems like a natural place to model this would be an association between the transition record and my user, but is there an easy way to hook into statesman to do this?

**Comment by greysteil** [comment]
You probably want to use metadata for this - `object.transition_to(:state, user: "some_user")` will set `user: "some_user"` as metadata on the transition.
