### ISSUE TITLE
Model.in_state(:valid) cannot identify correct transition model name

### ISSUE THREAD

**Issue by mecampbellsoup** [gocardless/statesman#220]
`Statesman::Adapters::ActiveRecordQueries#transition_refelection` calls `#transition_name`. However, that method gets the table name of the transition class like so:

``` ruby
        def transition_name
          transition_class.table_name.to_sym
        end
```

Therefore, `#transition_reflection` (which needs the association name, not the table name) is returning `nil`:

``` ruby
        def transition_reflection
          reflect_on_association(transition_name)
        end
```

In my case, I have `AuthToken::Transitions` that belong to an `AuthToken`. 

The code that revealed this potential bug to me was: `AuthToken.in_state(:valid)`:

```
[2] pry(AuthToken)> transition_name
:auth_token_transitions
[3] pry(AuthToken)> AuthToken.in_state(:valid)
NoMethodError: undefined method `table_name' for nil:NilClass
from /Users/mec/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/statesman-2.0.1/lib/statesman/adapters/active_record_queries.rb:50:in `model_table'
[4] pry(AuthToken)> 
```

Rails 5.0.0
Ruby 2.3.0

**Comment by mecampbellsoup** [comment]
@greysteil @isaacseymour are you guys maintainers still? Thanks :)

**Comment by mecampbellsoup** [comment]
Here is perhaps a better display of the bug. First I invoke `#transition_reflection` showing it starts out as `nil`. Then, I override the method to use the correct `#transition_name` which in this example is `AuthToken.has_many :transitions`:

```
    48: def model_table
 => 49:   binding.pry
    50:   transition_reflection.table_name
    51: end

[1] pry(AuthToken)> transition_reflection
nil
[2] pry(AuthToken)> transition_name
:auth_token_transitions
[3] pry(AuthToken)> def transition_name
[3] pry(AuthToken)*   :transitions
[3] pry(AuthToken)* end  
:transition_name
[4] pry(AuthToken)> transition_reflection
#<ActiveRecord::Reflection::HasManyReflection:0x007f87b0a143e0 @name=:transitions, @scope=nil, @options={:class_name=>"AuthToken::Transition", :autosave=>false}, @active_record=AuthToken(id: uuid, user_id: uuid, value: string, created_at: datetime, updated_at: datetime), @klass=nil, @plural_name="transitions", @automatic_inverse_of=nil, @type=nil, @foreign_type="transitions_type", @constructable=true, @association_scope_cache={}, @scope_lock=#<Thread::Mutex:0x007f87b0a14228>>
```

**Comment by mecampbellsoup** [comment]
I've ended up simply defining `AuthToken.transition_name` as follows to fix this: 

```ruby
    def transition_name
      :transitions
    end
    private_class_method :transition_name
```

**Comment by greysteil** [comment]
I *think* the issue here is that your `AuthTokenTransition` model isn't specifying its table name correctly. That's why `AuthToken.transition_name` is coming back as `auth_token_transitions`, rather than transitions. Statesman only looks for that table in the DB when `AuthToken.transition_reflection` is called, at which point it realises it isn't there and returns `nil.

If the above is true (I'm 99% confident), a better fix for your code would be to put `self.table_name = "transitions"` in your `AuthTokenTransition` model. I'll also put a PR into statesman to blow up with a clearer error message in this case.

**Comment by mecampbellsoup** [comment]
@greysteil yea, that's correct! Here's my model:

```ruby
class AuthToken < ApplicationRecord
  include Statesman::Adapters::ActiveRecordQueries

  has_many :transitions, class_name: "AuthToken::Transition", autosave: false
```
If I override `AuthToken::Transition.table_name = :transitions` my DB writes/reads won't work since the table's name is actually `:auth_token_transitions`.

P.S. thanks for getting back to me 😄

**Comment by daino3** [comment]
Hey gents. Running into this issue. It's trivial on our end to alias the relationship name, but this means that out of the box statesman doesn't play nice with ActiveRecord. Can we expedite this fix?
