### ISSUE TITLE
Documentation: Doesn't show how to ad logic on initial state

### ISSUE THREAD

**Issue by AAlvarez90** [gocardless/statesman#223]
The documentation shows how to execute code when moving from one stage to another, but it doesn't show how to execute code when the model is in the initial state.

**Comment by hmac** [comment]
I don't think it's possible to do this. You'd be adding something like
```ruby
after_transition(to: the_initial_state) do
  ...
end
```

which won't validate as you can't transition to the initial state.

If you've found a way to do this that could do with some documentation, I'd be keen to hear it!

Closing for now.
