### ISSUE TITLE
State Diagram

### ISSUE THREAD

**Issue by vassilevsky** [gocardless/statesman#236]
It would have been nice to have a rake task to produce a state diagram to visualize a complex state machine (written by someone else).

**Comment by vassilevsky** [comment]
I have implemented this in a separate gem because it is not needed in production:

https://github.com/vassilevsky/statesman-diagram

**Comment by Dorian** [comment]
I have this quick script that surprinsgly works :) https://gist.github.com/74160210e3f9d0d99f6c15024ee01062
