### ISSUE TITLE
Deprecate support for versions of Ruby/Rails that are out of security support

### ISSUE THREAD

**Issue by Sinjo** [gocardless/statesman#247]
Right now, [we test against](https://github.com/gocardless/statesman/blob/41b56bada52c123b52086b3bd1ec042cc18dd2a4/.travis.yml) some very old versions of Ruby/Rails, that aren't even receiving security support any more. Since we have a few features merged in already, let's get one more release out, then deprecate those versions.

**Comment by hmac** [comment]
Addressed by https://github.com/gocardless/statesman/pull/252

**Comment by stevebissett** [comment]
This has been merged and released in #252, so can be closed.

**Comment by hmac** [comment]
Very true
