### ISSUE TITLE
States method which lists all states

### ISSUE THREAD

**Issue by likelazyeyes** [gocardless/statesman#258]
Needed an important method for mapping states. Because we need graph for state machine with https://github.com/glejeune/Ruby-Graphviz

**Comment by danwakefield** [comment]
Hi @likelazyeyes 

It should be possible to get this information through `states` and `successors`.
For example:

```
class FooBar
  include Statesman::Machine

  # Happy states
  state :created, initial: true
  state :verified
  state :active

  # Sad states
  state :cancelled
  state :inactive

  # Transitions
  transition from: :created,   to: :verified
  transition from: :verified,  to: %i[active inactive cancelled]
  transition from: :cancelled, to: :active
  transition from: :inactive,  to: %i[active cancelled]
  transition from: :active,    to: %i[inactive cancelled]
end

FooBar.states
=> ["created", "verified", "active", "cancelled", "inactive"]
FooBar.successors
=> {
    "created"=>["verified"], 
    "verified"=>["active", "inactive", "cancelled"],
    "cancelled"=>["active"], 
    "inactive"=>["active", "cancelled"], 
    "active"=>["inactive", "cancelled"]
}
```

If this doesn't give you all of the information you need, it'd really help to provide an example so we can work with you to make Statesman better

**Comment by nickcampbell18** [comment]
We should add this to the readme if it isn't already there :)

**Comment by likelazyeyes** [comment]
Uv it's awesome, i was see noMethod Error when try Order.states.
OrderStateMachine.states running like a charm
I will start to code graphviz and i will share the codes here.
Maybe you add a graph generator
