### ISSUE TITLE
Drop support for Mongo

### ISSUE THREAD

**Issue by hmac** [gocardless/statesman#266]
This adapter isn't maintained and adds a lot of complexity to statesman.

Depending on how many people use it, I'd be keen to either split it out into a separate gem or remove it entirely.

**Comment by lawrencejones** [comment]
Recently the mongo tests have been failing, probably something to do with an awkward dependency pin: https://github.com/gocardless/statesman/pull/352#issuecomment-508791306

@hmarr @greysteil @danwakefield @isaacseymour @nickcampbell18 what are your thoughts on dropping mongo support entirely? I'm unsure anyone uses it, and on-going maintenance seems to be a bit of a pain.

**Comment by isaacseymour** [comment]
Fully :+1: - it seems weird anyway - can mongo support the transaction
requirements of Statesman?

**Comment by lawrencejones** [comment]
My hunch is that we added it because we could, not because we should. And that no one will have been using it in anger, so probably isn't rock solid

**Comment by hmarr** [comment]
It came in as a community contribution: https://github.com/gocardless/statesman/pull/8

I’m 👍 on dropping support though - if anyone does use it, splitting it out to a separate gem sounds like a great approach. Particularly if it can then be owned and maintained by people who actually use it.

**Comment by lawrencejones** [comment]
CC'ing @dluxemburg on this, as he was the original author of the mongo code.

Do you still use this Daniel? Or know anyone who does?

**Comment by lawrencejones** [comment]
Ok, let's do this.

In terms of how we release it: right now Statesman is v4.1.1. In alignment with our [compatibility policy](https://github.com/gocardless/statesman/blob/master/docs/COMPATIBILITY.md), we need to make adjustments to drop support for Ruby 2.2 and 2.3. We can also anticipate the Rails 6.0 release and look to drop Rails 4.2 as well.

https://github.com/gocardless/statesman/pull/351 aims to do all of this, and would come with a major version bump to v5.0.0. Given the source of issues with the mongo adapter come from a dependency issue with mongoid, and the latest versions of Rails are dependency-incompatible, my recommendation is that we bundle dropping of support for mongo into the v5.0.0 release.

Dropping mongo support is purely for developer convenience, so I don't see anyone benefitting from it being deployed separately of the Ruby 2.2/2.3 and Rails 4.2 support changes. This way we make one clean cut to v5.0.0 and minimise the major bumps from there.

If no one objects, I'll be looking to do this on Thursday. Feedback welcome!

**Comment by lawrencejones** [comment]
Rails 6 is out now, so let's try doing this next week.
