### ISSUE TITLE
`after_commit` only works if not wrapped in another transaction

### ISSUE THREAD

**Issue by jbourassa** [gocardless/statesman#281]
In the current implementation, `after_commit` callbacks are only ran after `COMMIT` if the calling code isn't in a transaction already. [Code causing this](https://github.com/gocardless/statesman/blob/master/lib/statesman/adapters/active_record.rb#L73-L80): 

```ruby
::ActiveRecord::Base.transaction do
  @observer.execute(:before, from, to, transition)
  unset_old_most_recent
  transition.save!
  @last_transition = transition
  @observer.execute(:after, from, to, transition)
end
@observer.execute(:after_commit, from, to, transition)
```

Now it's not very easy to fix. It could be done by dynamically pushing "after_commit" blocks on the Transaction class, but that is hacky and brittle. I'm open to any other implementation idea, if you want me to work on this!

**Comment by danwakefield** [comment]
Sorry we didn't respond to this but good news now; This has been fixed in the latest major release.
