### ISSUE TITLE
Setting most_recent doesn't change updated_at

### ISSUE THREAD

**Issue by NGMarmaduke** [gocardless/statesman#284]
The Active Record adapter uses update_all to unset the `most_recent` boolean.
This results in the `updated_at` column not being accurate - causing us issues when using [stitch](https://www.stitchdata.com/) ELT which relies on the `updated_at` for detecting row changes in the DB.

https://github.com/gocardless/statesman/blob/c12a30309ce2a99240eb499f4f06b5c0e7e72e2b/lib/statesman/adapters/active_record.rb#L97-L101

**Comment by danwakefield** [comment]
Internally we warn on use of `update_all` because of this very reason so the change seems sensible. 
Since this would change behaviour in a subtle way it'll require at least a minor version bump.

**Comment by vvondra** [comment]
Btw the second part of this change might be very nice from a performance standpoint.

We have long running statemachines (low thousands of transitions per model, continuously growing) and `UPDATE "model_transitions" SET "most_recent" = ? WHERE "model_transitions"."model_id" = ?` shows up as the heaviest query in terms of IO by two orders of magnitude.
