### ISSUE TITLE
Transition class generated for mongoid is broken

### ISSUE THREAD

**Issue by tomclose** [gocardless/statesman#29]
Using the transition class generated for the mongoid adapter will lead to errors like:

    NameError: undefined method `statesman_metadata' for class ...

This is because the `include Statesman::Adapters::MongoidTransition` tries to alias `statesman_metadata`, which isn't defined at that point.

A short term fix is to move this line below `field :statesman_metadata`:

    class OrderTransition
      include Mongoid::Document

      field :to_state, type: String
      field :sort_key, type: Integer
      field :statesman_metadata, type: Hash

      # this has to be after the statesman_metadata declaration
      include Statesman::Adapters::MongoidTransition
      # ....

A longer term solution could involve declaring the fields in `Statesman::Adapters::MongoidTransition` module, similar to how it is done here: https://github.com/aq1018/mongoid-history/blob/master/lib/mongoid/history/tracker.rb.

**Comment by greysteil** [comment]
@tomclose - sorry this took so long!
