### ISSUE TITLE
How come I get a lot of sort_key uniqueness validation errors?

### ISSUE THREAD

**Issue by ericgross** [gocardless/statesman#333]
Frequently I'll get this error in statesman 3.5.0 from my background jobs:

`Validation failed: Sort key has already been taken`

from this line of code:

`Statesman::Machine.retry_conflicts(1) { order.transition_to!(:recipe_customized) }`

I see that `retry_conflicts` only rescues from `TransitionConflictError` exceptions - but I think it should also rescue from (and retry) the error I am seeing - is that right?

**Comment by danwakefield** [comment]
Statesman should be raising `TransitionConflictError` in this case. See below.

https://github.com/gocardless/statesman/blob/50640ee26da095927ae356f1fb95759563b23267/lib/statesman/adapters/active_record.rb#L35-L40

https://github.com/gocardless/statesman/blob/50640ee26da095927ae356f1fb95759563b23267/lib/statesman/adapters/active_record.rb#L120-L123

Can you tell me the Database and version you are using and I'll try to figure out if `transition_conflict_error?` should be changed in some way.
