### ISSUE TITLE
`check_missing_methods!` method not working as intended

### ISSUE THREAD

**Issue by NGMarmaduke** [gocardless/statesman#369]
Currently the `check_missing_methods!` on `active_record_queries.rb` looks like:

https://github.com/gocardless/statesman/blob/b7e1a9c92884d90def039a22176a2da771c04e20/lib/statesman/adapters/active_record_queries.rb#L5-L7

This issue line being:
```ruby
reject { |_method| base.respond_to?(:method) } 
``` 

All ruby classes will respond to the `method` method, and therefore this predicate will never return false. This results in the guard always returning early and therefore the subsequent error is never raised. 

Presumable the check should look something like:
```ruby
reject { |method| base.respond_to?(method) } 
```

I'm happy to PR when I have time

**Comment by danwakefield** [comment]
Thanks for raising this issue. https://github.com/gocardless/statesman/pull/364 is in progress of addressing it, I'll poke the author and ask when they think it will be finished.
