### ISSUE TITLE
Incorrect machine current state after transition

### ISSUE THREAD

**Issue by pedro-pedrosa** [gocardless/statesman#387]
I ran into a scenario where a transition was created on the database but the state machine is still showing the old state.

This is happening because, for some reason, the `created_at` field of the state transition in the database is incorrect. This is especially weird considering that the `created_at` value is more recent than the `updated_at` value. I do not directly change the value of the `created_at` field in my application so I don't know exactly why this happened, but I believe it was the result of a race condition.

Anyway, what is happening here is that when the machine goes from the initial state to state A and then to state B, in some rare cases, the transition to state B has a `created_at` value that is earlier than the `created_at` value of the transition to state A. The `updated_at` value of the transition to A is before the `created_at` value of the transition to B (setting `most_recent` to `NULL`) so I know it transitioned to A before transitioning to B.

What I don't understand is why Statesman is looking at the `created_at` value to retrieve the current state of the machine:
```
irb(main):004:0> machine.current_state
  StateTransitions::Machine Load (194.1ms)  SELECT  "state_transitions".* FROM "state_transitions" WHERE "state_transitions"."type" IN ('StateTransitions::Machine') AND "state_transitions"."transitable_id" = $1 AND "state_transitions"."transitable_type" = $2 ORDER BY "state_transitions"."created_at" DESC, "state_transitions"."sort_key" DESC LIMIT $3  [["transitable_id", "4450b957-5027-4ff2-b96a-88f7fc9730ab"], ["transitable_type", "Model"], ["LIMIT", 1]]
=> "queued"
```

Is there a reason for not ordering by `sort_key` or even just getting the `most_recent` one?

Is it possible that the incorrect `created_at` value is an issue with Statesman or Rails?

**Comment by danwakefield** [comment]
Can you provide the version of the library you are using?

As far as I can tell the current library does use `sort_key`

https://github.com/gocardless/statesman/blob/38db90190c66969461570a24a3e1edde2dad5d8b/lib/statesman/machine.rb#L193-L196

calls

https://github.com/gocardless/statesman/blob/3c370ad1e3463c763a4d3c7fdd2b81403090196e/lib/statesman/machine.rb#L206-L208

which calls

https://github.com/gocardless/statesman/blob/38db90190c66969461570a24a3e1edde2dad5d8b/lib/statesman/adapters/active_record.rb#L58-L64

which calls 

https://github.com/gocardless/statesman/blob/38db90190c66969461570a24a3e1edde2dad5d8b/lib/statesman/adapters/active_record.rb#L48-L56

**Comment by pedro-pedrosa** [comment]
yeah I just saw that in the source as well. I'm using `4.0.0`

**Comment by pedro-pedrosa** [comment]
well actually looking closer to the query, it does sort by `sort_key`, *after*  sorting by `created_at`, so the `sort_key` only has any effect if `created_at` is the same.

**Comment by danwakefield** [comment]
Ok, inside the library we don't sort by `created_at` anywhere. Given this I have to assume that the definition of the association on the parent model is incorrect.

e.g
```
class Order < ActiveRecord::Base
  has_many :order_transitions
end
```
If you have redefined `order_transitions` on the parent model to include the `created_at` ordering it may not return the correct results.

**Comment by pedro-pedrosa** [comment]
correct. all of my state transition models are inheriting from a base `ApplicationRecord` which sets:

```ruby
default_scope { order(created_at: :asc) }
```

this results in the above incorrect behavior. sorry for any confusion.

**Comment by danwakefield** [comment]
No worries, Good luck with fixing it.
