### ISSUE TITLE
[meta] Is gocardless/statesman-events still being maintained?

### ISSUE THREAD

**Issue by nickgrim** [gocardless/statesman#393]
Statesman 4.1.3 changed the public API of `TransitionFailedError`, [which broke statesman-events](https://github.com/gocardless/statesman-events/issues/4), and that issue and PR don't seem to be getting any love.

All of the commits in statesman-events seem to be by one person (@greysteil) who doesn't seem to work at GoCardless any more, so I was wondering whether it's been abandoned - officially or unofficially - or whether it's just been left without a maintainer and slipped through the cracks.

**Comment by danwakefield** [comment]
Sorry about that. We don't use that internally and given the only history it has is the initial commit I'd say its completely maintained by us.

Since there is a PR in place I will merge that and update the readme to make it clear that the gem is unsupported.

**Comment by dstockdale** [comment]
I wonder if you should still continue to have a section in the main Statesman readme about the statesman-events gem if when you go to it, it says **THIS REPO IS UNMAINTAINED. PLEASE DO NOT USE IT**. It's just alarming. By the way the statesman-events gem works absolutely fine, as it has done for years (even if no one is looking after it). It's nice and simple. I way prefer using Statesman over the bloated alternatives. Thank you 🙏🙏🙏.

**Comment by lawrencejones** [comment]
That's a good point about the message. @danwakefield how do you feel about changing that to something more like "contributions only"?

Example is kingpin. We use this library all over the place despite it being maintenance-only. It's feature stable and works really well, so why would we use something different?

https://github.com/alecthomas/kingpin#contributions-only

**Comment by nickgrim** [comment]
@dstockdale:
> By the way the statesman-events gem works absolutely fine…

…apart from [the changed behaviour around non-existent events](https://github.com/gocardless/statesman-events/issues/4) which is where this all started.

@lawrencejones:
> how do you feel about changing [the message on statesman-events](https://github.com/gocardless/statesman-events) to something more like "contributions only"?

I can't speak for @danwakefield, but I was reading that message and his comment here as "GoCardless don't use it and have no interest in maintaining it".

**Comment by lawrencejones** [comment]
Yep, you have my apologies for the slow response- of the engineers who worked at GC back when statesman-events was created, only three are still here. It's very existence was a bit of a surprise to us, and no one was configured to get notifications on that repo!

@nickgrim, you seem to have felt the most pain here. What would be your preference, if you had to decide:
1. Leave the current "DO NOT USE" message
2. Change it to indicate that you use it at your own risk, and upstream Statesman doesn't attempt to maintain compatibility with it
3. Archive the repository to demonstrate this project has been sunset

I have few opinions on either of these, as (to my knowledge) we've never used statesman-events at GC.

**Comment by nickgrim** [comment]
Honestly, we've migrated our project to just use basic `statesman` without `statesman-events` because we didn't want to attempt to maintain compatibility ourselves.

With that caveat, I'd probably choose option 2 of those given, possibly with (a) a note saying you're looking for maintainers and/or (b) a link to a better-maintained fork, if/when such a thing exists. Given I'm not a user anymore though, @dstockdale is probably a better person to ask.
