### ISSUE TITLE
ActiveRecord Adapter & Multiple Databases

### ISSUE THREAD

**Issue by ckorhonen** [gocardless/statesman#406]
I've recently updated to Rails 6.0 and have ran into an issue with this gem and the new support for multiple databases.

I have two databases in my application, and I want the transition class in my state machine to live in the secondary database.

Everything works, until I try and transition state:

``` ruby
foo.transition_to!(:bar)

   (0.4ms)  ROLLBACK
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "foo_transitions" does not exist
LINE 1: UPDATE "foo_transitions" SET "most_recent" = FALSE, "upda...
               ^
from /usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql_adapter.rb:675:in `exec_params'
Caused by PG::UndefinedTable: ERROR:  relation "foo_transitions" does not exist
LINE 1: UPDATE "foo_transitions" SET "most_recent" = FALSE, "upda...
```

It appears that Statesman is trying to write my transition class to the wrong database.

If I wrap the code, everything works correctly:

``` ruby
ActiveRecord::Base.connected_to(database: :secondary) do
     foo.transition_to!(:bar)
end
```

Models are setup as per the [Rails guide](https://guides.rubyonrails.org/active_record_multiple_databases.html), with everything residing in the secondary database inheriting from an abstract class.

Based on a cursory glance at the code it looks like `Statesman::Adaptors::ActiveRecord` is operating in the context of `ActiveRecord::Base.connection` rather than using whatever is utilized by the transition class.

**Comment by ckorhonen** [comment]
Added a rough PR which appears to fix this - no regressions noted for any of my state machines, using either primary or secondary DBs.

**Comment by robotex82** [comment]
We are having the same issues by upgrading from 3.4.1 to 10.0.0. Any chances to have this PR updated and merged?

**Comment by stephenbinns** [comment]
Fixed in https://github.com/gocardless/statesman/pull/522
