### ISSUE TITLE
State Machine after transition fails if used on initial state with DB persistence

### ISSUE THREAD

**Issue by nacengineer** [gocardless/statesman#436]
If you try to hook into the after transition callback for the initial state you will trigger the error 

Cannot transition to initial state 'name of your initial state' (Statesman::InvalidTransitionError)

This is with transitions persisted to the database. 

Once I realized what the error is basically telling me. 

"Hey dummy, this thing doesn't exactly exist yet and now you've created a race condition around this transition" 

It made sense, but the error raise didn't really help me TBH. 

Not sure if it's possible to add a check on the after transition for the initial transition and maybe raise something indicating this is the issue. I know this is a weird corner case and is I'm assuming it's solved with the "after_commit: true" setting but it still took me a little while to figure out. Maybe this will help the next person to come along, which will probably be a future me but I digress. 

Thanks for the awesome gem. 🙂

**Comment by thom-oman** [comment]
Hey @nacengineer thanks for your issue and apologies for the delays replying.

So when we create a callback we check that the state we are transitioning _to_ is neither the initial state nor _from_ the terminal state. So the error you're seeing is from this
```
# Check that the 'to' state is not initial
def validate_not_to_initial_state(to)
  unless to.nil? || successors.values.flatten.include?(to)
    raise InvalidTransitionError,
          "Cannot transition to initial state '#{to}'"
  end
end
```
So this has nothing to do with a race condition, we just do not allow transitions back to the initial state. Also FYI, we never persist the initial state to the database (for the AR adapter).

Let me know if I've misunderstood 😅

**Comment by thom-oman** [comment]
Going to close this, lemme know if I've misunderstood and we can reopen

**Comment by nacengineer** [comment]
Sry for the delayed response. 

I think maybe you did. 

Basically I'm saying if you assign an after_transaction to the initial state the app just blows up. And the error doesn't really let you know the after hook is why it's blowing up. 

In my case I wasn't transitioning anything or creating any new transitions. The main page of my application is blowing up on a simple lookup to the Model querying for all the things that are in the initial state. 

Maybe there is nothing that can be done w.r.t. this error but I at least wanted to raise the issue in your issue log.

**Comment by danwakefield** [comment]
Unfortunately to make the error message better we would need to implement named transitions. (Suggested in https://github.com/gocardless/statesman/issues/254)

Internally we've never found the time to do this as errors such as this are caught if there are any tests that initialize the machine (and we test everything)

e.g using the Order classes from the readme as examples

```
class OrderStateMachine
    include Statesman::Machine

    state :A, initial: true
    state :B

    transition from: :A, to: :B

    after_transition(to: :A) do
	    1 + 1
    end
end

# and in `order_state_machine_spec`

subject(:machine) do
    described_class.new(FactoryBot.create(:order), transition_class: OrderTransition)
end

it "works" do
	expect { machinee.transition_to!(:B) }.to change { machine.current_state }
end
```

would immediately fail as part of the test suite with
```
❯ rspec spec/state_machines/order_spec.rb

An error occurred while loading ./spec/state_machines/order_spec.rb.
Failure/Error: 
  after_transition(to: :A) do
      1 + 1
  end

Statesman::InvalidTransitionError:
  Cannot transition to initial state 'A'
```

**Comment by nacengineer** [comment]
cool. I can understand that. I think having a closed issue in the issue tracker should be good enough for now. Maybe put something in the docs saying don't do this on the initial state when you go to update the docs next time but I think this closed issue should suffice. Thanks for the awesome gem! 😀
