### ISSUE TITLE
Ability to guard with user permissions

### ISSUE THREAD

**Issue by sebbacon** [gocardless/statesman#44]
This isn't really a bug, more a question, but wasn't sure where else to ask it.

A common pattern for a guard is to check if the currently logged in user has the requisite permission. What pattern do you suggest for this, given we can't pass any context to the `allowed_transitions` method?

**Comment by mbhnyc** [comment]
Indeed, this is super old but it would be nice to be able to pass context into can_transition_to? that would reach down to the guard callback, so i could verify that only certain roles have the ability to transitions to certain states.  Anyway, useful unless there's an elegant way to do this that i'm missing!
