### ISSUE TITLE
Calling `reload` on an object should reload its state as well

### ISSUE THREAD

**Issue by jcollins-gc** [gocardless/statesman#487]
Given a Statesman-managed object, I would like to have the state reload by default if `reload` is called on the object.

For instance, say I have this object in memory in process A:
```
thing = ThingWithStateMachine.find(1)
state = thing.current_state # :new
```

And process B transitions it:
`ThingWithStateMachine.transition_to(:started)`

I should be able to reload it in process A and get the new state:
`thing.reload.current_state # is :new, should be :started`

**Comment by zerc** [comment]
https://github.com/gocardless/statesman/pull/507

**Comment by zerc** [comment]
Fixed in https://github.com/gocardless/statesman/pull/507
