### ISSUE TITLE
ActiveRecord validations

### ISSUE THREAD

**Issue by jsmestad** [gocardless/statesman#57]
Does statesman have a best practice on how do the following?

``` ruby
    state :first_gear, :second_gear do
      validates_presence_of :seatbelt_on
    end
```

This is very useful for "wizard" workflows where the user gradually enters more data as they go through the workflow. Also using `ActiveRecord::Validations` has the added benefit of form integration (things like presence or uniqueness validation messages get displayed)

**Comment by bjeanes** [comment]
I'm surprised there isn't more guidance on this issue. The solution does not directly address the core of the question: validations which only apply in certain states.

The answer merely shows how to to ensure that the model is _generally_ valid when transitioning between two given states.

Are you proposing that the model look something like:

```rb
validates :seatbelt_on, presence: true, if: ->(car) { state_machine.current_state == "second_gear" }
```

Would `current_state` even return the new state in a `guard_transition` (my assumption is that the guard happens first)?

**Comment by bjeanes** [comment]
Or perhaps this would be enough to cause a rollback and a failure to transition?

```rb
# model
validates :seatbelt_on, presence: true, if: ->(car) { car.in_state?(:second_gear) }

# state machine
after_transition do |model, transition|
  model.touch!
end
```
