### ISSUE TITLE
Optimize MySQL indexes?

### ISSUE THREAD

**Issue by mkdynamic** [gocardless/statesman#59]
Currently, there are 2 indexes added [by default in the migration for the ActiveRecord transition model](https://github.com/gocardless/statesman/blob/master/lib/generators/statesman/templates/create_migration.rb.erb#L11). Since all queries will always include the [foreign key for the model](https://github.com/gocardless/statesman/blob/master/lib/statesman/adapters/active_record.rb#L56), I believe it would be more optimal to use 1 index.

```ruby
# Current indexes:
add_index :model, :model_id
add_index :model, [:sort_key, :model_id], unique: true

# Suggested index:
add_index :model, [:model_id, :sort_key], unique: true
```

Assuming that the query to obtain the transition history always includes the foreign key (`model_id`) and is sorted by `sort_key`, this seems optimal for 2 reasons:

1. Reduces from 2 indexes to 1, which will reduce insert time
2. Because the `sort_key` comes last, I believe MySQL can use the index to sort the results, rather than having to perform a file sort

Some quick EXPLAIN analysis seems to confirm 2.

Does this seem sane? Let me know I misunderstood/overlooked anything.

**Comment by greysteil** [comment]
Closing now https://github.com/gocardless/statesman/pull/92 is merged.
