### ISSUE TITLE
Documentation - How to test Statesman implementations

### ISSUE THREAD

**Issue by pacso** [gocardless/statesman#77]
Hello,

Considering this is quite a new project, it's no surprise that the documentation is a little thin. There's enough to get you going with a working state machine, however there's no mention of the best way to test states/transitions/guards/etc from within an application that uses statesman.

I'm more than happy to help contribute towards the documentation, but just wondered if you have any details on how you currently test models which have a statesman state machine behind them? Do you have any RSpec custom matchers? Or do you not test the implementation of your state machines in a unit-test style but rather in functional tests?

**Comment by mecampbellsoup** [comment]
Hey @pasco @jackfranklin would you guys mind posting the contents of one of your `SomeModelTransition` factory(-ies)? We don't use Factory Girl, so I am curious to see how you guys populate the `null: false` columns on your `OrderTransition` model, for example `sort_key` and `most_recent`. Thanks :)

**Comment by pacso** [comment]
Hi @mecampbellsoup - the FactoryGirl solution I mentioned above is actually what I'm still using. It provides enough to be able to unit test my state machine. For integration tests I don't use any factories for orders or transitions.

**Comment by mecampbellsoup** [comment]
Oh okay. So the factory must be filling in defaults for those `null: false`
attributes. What does `ModelTransitionFactory.build` return for you?

**Comment by ArthurN** [comment]
@mecampbellsoup You can just make `sort_key: 0` and `most_recent: true` as it would be the first (and presumably only) transition at the time.

I find this to be a fairly decent solution to bypassing guards and just putting the model into some state in order to be able to test business logic. Thanks @pacso!
