### ISSUE TITLE
DEPRECATION WARNING when using in_state and not_in_state

### ISSUE THREAD

**Issue by netikular** [gocardless/statesman#93]
I'm using rails 4.0.8 and receiving: 

DEPRECATION WARNING: It looks like you are eager loading table(s) (one of: requests, transition1, transition2, floor) that are referenced in a string SQL snippet.

I've resolved the problem on a copy of my own, I'll submit a pull request to discuss if this is the way you would like to fix it.

**Comment by greysteil** [comment]
Closing since https://github.com/rails/rails/commit/d1e7cd14c29f1ef45f2f36e79cd99eb580036991 removes this deprecation.

**Comment by greysteil** [comment]
@netikular - thanks all the same for this, and sorry it's taken us this long to get to the bottom of it!
